### ISSUE TITLE
ESM-1.20.1-1.0.0.jar game completely freezes on world load up chunk loading Etc

### ISSUE THREAD

**Issue by FullMetalMaster** [hyperhipp0/NESM#4]
i have tryed editing configs etc and there's the small chance percentage that when you reload the world everything runs perfectly fine put on the first load up it always dies chunks stop loading the game just crashes

**Comment by StockiesLad** [comment]
```
at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.m_8055_(Level.java:3543)
	at TRANSFORMER/nightmareesm@1.0.0/com.esm.nightmare.DuplicateMob.isPositionGood(DuplicateMob.java:102)
	at TRANSFORMER/nightmareesm@1.0.0/com.esm.nightmare.DuplicateMob.Clone(DuplicateMob.java:63)
	at TRANSFORMER/nightmareesm@1.0.0/com.esm.nightmare.DuplicateMob.<init>(DuplicateMob.java:44)
	at TRANSFORMER/nightmareesm@1.0.0/com.esm.nightmare.NightmareMain.onEntitySpawn(NightmareMain.java:156)
	at TRANSFORMER/nightmareesm@1.0.0/com.esm.nightmare.__NightmareMain_onEntitySpawn_FinalizeSpawn.invoke(.dynamic)
	```
the code for spawning in the mobs is broken.

**Comment by StockiesLad** [comment]
fixed in https://github.com/hyperhipp0/NESM/pull/5

**Comment by ZaCloud** [comment]
> fixed in [#5](https://github.com/hyperhipp0/NESM/pull/5)

Shouldn't this thread be closed/marked as completed or however that works then?
